chore(deps): revert upgrade of @storybook/csf
To solve a type error

  Error: src/storybook.tsx(314,47): error TS2344: Type 'ReactFramework' does not satisfy the
  constraint 'Renderer'.
    Property 'canvasElement' is missing in type 'ReactFramework' but required in type 'Renderer'.